import type { Restaurant } from "./types";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Pizza Palace",
    cuisine: "Italian",
    rating: 4.5,
    reviews: 150,
    address: "123 Pizza Lane, Foodville",
    deliveryTime: "25-35 min",
    priceRange: "20-40",
    imageId: "restaurant-1",
    menu: [
      {
        id: "m1-1",
        name: "Margherita Pizza",
        description: "Classic delight with 100% real mozzarella cheese",
        price: 12.99,
        imageId: "menu-item-1",
      },
      {
        id: "m1-2",
        name: "Pepperoni Pizza",
        description: "A classic with pepperoni and cheese",
        price: 14.99,
        imageId: "menu-item-1",
      },
      {
        id: "m1-3",
        name: "Veggie Supreme",
        description: "A pizza loaded with fresh vegetables",
        price: 13.99,
        imageId: "menu-item-1",
      },
    ],
  },
  {
    id: "2",
    name: "Burger Barn",
    cuisine: "American",
    rating: 4.2,
    reviews: 200,
    address: "456 Burger Blvd, Foodville",
    deliveryTime: "20-30 min",
    priceRange: "15-30",
    imageId: "restaurant-2",
    menu: [
      {
        id: "m2-1",
        name: "Classic Cheeseburger",
        description: "Juicy beef patty with cheese, lettuce, and tomato",
        price: 9.99,
        imageId: "menu-item-2",
      },
      {
        id: "m2-2",
        name: "Bacon Burger",
        description: "The classic, but with crispy bacon",
        price: 11.99,
        imageId: "menu-item-2",
      },
      {
        id: "m2-3",
        name: "Veggie Burger",
        description: "A delicious plant-based patty",
        price: 10.99,
        imageId: "menu-item-2",
      },
    ],
  },
  {
    id: "3",
    name: "Sushi Station",
    cuisine: "Japanese",
    rating: 4.8,
    reviews: 120,
    address: "789 Sushi St, Foodville",
    deliveryTime: "35-45 min",
    priceRange: "30-60",
    imageId: "restaurant-3",
    menu: [
      {
        id: "m3-1",
        name: "California Roll",
        description: "Crab, avocado, and cucumber",
        price: 8.99,
        imageId: "menu-item-3",
      },
      {
        id: "m3-2",
        name: "Spicy Tuna Roll",
        description: "Tuna, spicy mayo, and cucumber",
        price: 9.99,
        imageId: "menu-item-3",
      },
      {
        id: "m3-3",
        name: "Dragon Roll",
        description: "Eel, crab, and avocado",
        price: 12.99,
        imageId: "menu-item-3",
      },
    ],
  },
  {
    id: "4",
    name: "Curry Corner",
    cuisine: "Indian",
    rating: 4.6,
    reviews: 180,
    address: "101 Curry Close, Foodville",
    deliveryTime: "30-40 min",
    priceRange: "25-50",
    imageId: "restaurant-4",
    menu: [
      {
        id: "m4-1",
        name: "Chicken Tikka Masala",
        description: "Creamy and rich tomato-based curry",
        price: 15.99,
        imageId: "restaurant-4",
      },
      {
        id: "m4-2",
        name: "Paneer Butter Masala",
        description: "Vegetarian delight in a buttery sauce",
        price: 14.99,
        imageId: "restaurant-4",
      },
      {
        id: "m4-3",
        name: "Garlic Naan",
        description: "Soft bread with garlic and butter",
        price: 3.99,
        imageId: "restaurant-4",
      },
    ],
  },
    {
    id: "5",
    name: "The Salad Spot",
    cuisine: "Healthy",
    rating: 4.9,
    reviews: 95,
    address: "222 Green Way, Foodville",
    deliveryTime: "15-25 min",
    priceRange: "15-25",
    imageId: "restaurant-5",
    menu: [
      {
        id: "m5-1",
        name: "Caesar Salad",
        description: "Crisp romaine, croutons, and parmesan",
        price: 10.99,
        imageId: "restaurant-5",
      },
      {
        id: "m5-2",
        name: "Greek Salad",
        description: "Feta, olives, cucumber, and tomatoes",
        price: 11.99,
        imageId: "restaurant-5",
      },
    ],
  },
  {
    id: "6",
    name: "Taco Town",
    cuisine: "Mexican",
    rating: 4.4,
    reviews: 250,
    address: "333 Fiesta Ave, Foodville",
    deliveryTime: "20-30 min",
    priceRange: "15-35",
    imageId: "restaurant-8",
    menu: [
      {
        id: "m6-1",
        name: "Carne Asada Tacos",
        description: "Three grilled steak tacos",
        price: 12.99,
        imageId: "restaurant-8",
      },
      {
        id: "m6-2",
        name: "Chicken Burrito",
        description: "Large burrito with chicken, rice, and beans",
        price: 13.99,
        imageId: "restaurant-8",
      },
    ],
  },
];
